language: python
python:
  - 2.7

env:
  - TOXENV=py-pyqt
  - TOXENV=py-pyside

matrix:
  include:
    - python: 3.4
      env: TOXENV=py-pyside

    - python: 3.6
      env: TOXENV=py-pyqt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - xvfb

# command to install dependencies
install:
  - pip install . --process-dependency-links --trusted-host github.com

script:
  - tox
